services:
  postgres:
    image: postgres:16-alpine
    container_name: intern_budgethold-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=intern-budgethold
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intern_budgethold-network

volumes:
  postgres_data:

networks:
  intern_budgethold-network:
    driver: bridge
